package com.zhitu.service;
import com.zhitu.common.Jsons;
import com.zhitu.engine.TrustScoreEngine;
import com.zhitu.repository.Store;
import org.springframework.stereotype.Service;
import java.util.*;
@Service
public class TrustedAuditService {
 private final Store store;private final Jsons jsons;private final TrustScoreEngine trust;
 public TrustedAuditService(Store store,Jsons jsons,TrustScoreEngine trust){this.store=store;this.jsons=jsons;this.trust=trust;}
 public List<Map<String,Object>> pending(){List<Map<String,Object>>out=new ArrayList<>();for(var c:store.list("SELECT * FROM emerging_candidate WHERE status='AUTO_CANDIDATE' ORDER BY hallucination_risk DESC",Map.of())){Map<String,Object>x=new LinkedHashMap<>(c);x.put("targetType","EMERGING_ROLE");x.put("title",c.get("candidate_name"));x.put("risk",c.get("hallucination_risk"));out.add(x);}for(var e:store.list("SELECT * FROM evolution_event WHERE status='AUTO_DETECTED' ORDER BY confidence",Map.of())){Map<String,Object>x=new LinkedHashMap<>(e);x.put("targetType","EVOLUTION");x.put("title",e.get("role_name")+" · "+e.get("skill_name"));x.put("risk",1-((Number)e.get("confidence")).doubleValue());out.add(x);}return out;}
 public Map<String,Object> decision(String type,long id,String action,String reviewer,String comment,Map<String,Object>patch){String normalized=action.toUpperCase(Locale.ROOT);if(!Set.of("APPROVE","REJECT","MODIFY").contains(normalized))throw new IllegalArgumentException("action 必须为 APPROVE、REJECT 或 MODIFY");String table=type.equalsIgnoreCase("EMERGING_ROLE")?"emerging_candidate":type.equalsIgnoreCase("EVOLUTION")?"evolution_event":"";if(table.isBlank())throw new IllegalArgumentException("未知审核类型");Map<String,Object>before=store.one("SELECT * FROM "+table+" WHERE id=:id",Map.of("id",id));String status=normalized.equals("APPROVE")?"APPROVED":normalized.equals("REJECT")?"REJECTED":"MODIFIED";
  if(table.equals("emerging_candidate"))store.update("UPDATE emerging_candidate SET status=:s,definition=COALESCE(:d,definition),required_skills=COALESCE(:r,required_skills),bonus_skills=COALESCE(:b,bonus_skills) WHERE id=:id",params("s",status,"d",patch==null?null:patch.get("definition"),"r",patch==null?null:patch.get("requiredSkills"),"b",patch==null?null:patch.get("bonusSkills"),"id",id));else store.update("UPDATE evolution_event SET status=:s,explanation=COALESCE(:e,explanation) WHERE id=:id",params("s",status,"e",patch==null?null:patch.get("explanation"),"id",id));Map<String,Object>after=store.one("SELECT * FROM "+table+" WHERE id=:id",Map.of("id",id));double risk=before.get("hallucination_risk")instanceof Number n?n.doubleValue():1-((Number)before.getOrDefault("confidence",.5)).doubleValue();long aid=store.insert("INSERT INTO audit_record(target_type,target_id,action,reviewer,comment,before_json,after_json,risk_score) VALUES(:t,:id,:a,:r,:c,:b,:af,:risk)",params("t",type,"id",id,"a",normalized,"r",reviewer==null||reviewer.isBlank()?"管理员":reviewer,"c",comment,"b",jsons.write(before),"af",jsons.write(after),"risk",risk));if(table.equals("emerging_candidate")&&normalized.equals("APPROVE"))publishCandidate(after);return Map.of("auditId",aid,"status",status,"target",after);
 }
 private void publishCandidate(Map<String,Object>c){String name=String.valueOf(c.get("candidate_name"));if(store.maybe("SELECT id FROM job_role WHERE role_name=:n",Map.of("n",name)).isPresent())return;store.insert("INSERT INTO job_role(role_name,normalized_name,tech_stack,level_name,definition,responsibilities,scenarios,status,confidence) VALUES(:n,:nn,'大模型应用','新兴岗位',:d,:r,:s,'PUBLISHED',:c)",params("n",name,"nn",name.toLowerCase(),"d",c.get("definition"),"r",c.get("responsibilities"),"s",c.get("scenarios"),"c",c.get("confidence")));}
 public List<Map<String,Object>> history(){return store.list("SELECT * FROM audit_record ORDER BY id DESC LIMIT 200",Map.of());}
 private Map<String,Object>params(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put(String.valueOf(v[i]),v[i+1]);return m;}
}
